"""make datetime columns timezone aware

Revision ID: 84b37008b0a2
Revises: b5723e7807a2
Create Date: 2026-03-01 12:18:33.918552+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84b37008b0a2'
down_revision: Union[str, Sequence[str], None] = 'b5723e7807a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'alert_type',
               existing_type=sa.VARCHAR(length=100),
               comment='drought_risk, vegetation_decline.',
               existing_comment='drought_risk, vegetation_decline, anomaly, pest_stress, etc.',
               existing_nullable=False)
    op.alter_column('alerts', 'detected_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('alerts', 'resolved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('ingestion_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='When job execution started',
               existing_nullable=True)
    op.alter_column('ingestion_jobs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='When job finished (success or failure)',
               existing_nullable=True)
    op.alter_column('parcels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('parcels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('parcels', 'last_data_synced_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp of last successful data sync(any job)',
               existing_nullable=True)
    op.alter_column('parcels', 'next_sync_scheduled_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='When to schedule next ingestion job',
               existing_nullable=True)
    op.alter_column('raster_stats', 'processed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('time_series', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###

    
    # creating a trigger for calculating area_hectares from geometry column,
    # to avoid having to calculate it in the application code and ensure it's always accurate based on the geometry
    # added in here(is the current head when I added this trigger)
    op.execute("""
    CREATE OR REPLACE FUNCTION calculate_parcel_area()
    RETURNS TRIGGER AS $$
    BEGIN
        IF NEW.geometry IS NOT NULL THEN
            NEW.area_hectares := ROUND(
            (ST_Area(NEW.geometry::geography) / 10000)::numeric, 
            4
            ); -- ST_Area calculates the area of a polygonal geometry and our parcel.geometry is a polygon(https://postgis.net/docs/ST_Area.html)
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    # attach trigger to parcels table
    op.execute("""
    CREATE TRIGGER trigger_calculate_parcel_area
        BEFORE INSERT OR UPDATE ON parcels
        FOR EACH ROW EXECUTE FUNCTION calculate_parcel_area();
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_series', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('raster_stats', 'processed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('parcels', 'next_sync_scheduled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='When to schedule next ingestion job',
               existing_nullable=True)
    op.alter_column('parcels', 'last_data_synced_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp of last successful data sync(any job)',
               existing_nullable=True)
    op.alter_column('parcels', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('parcels', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='When job finished (success or failure)',
               existing_nullable=True)
    op.alter_column('ingestion_jobs', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='When job execution started',
               existing_nullable=True)
    op.alter_column('ingestion_jobs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('alerts', 'resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('alerts', 'detected_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('alerts', 'alert_type',
               existing_type=sa.VARCHAR(length=100),
               comment='drought_risk, vegetation_decline, anomaly, pest_stress, etc.',
               existing_comment='drought_risk, vegetation_decline.',
               existing_nullable=False)
    # ### end Alembic commands ###
