"""users table

Revision ID: c762fc836302
Revises: 84b37008b0a2
Create Date: 2026-03-17 14:29:20.805789+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c762fc836302'
down_revision: Union[str, Sequence[str], None] = '84b37008b0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.add_column('parcels', sa.Column('owner_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_parcels_owner_id'), 'parcels', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'parcels', 'users', ['owner_id'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parcels', type_='foreignkey')
    op.drop_index(op.f('ix_parcels_owner_id'), table_name='parcels')
    op.drop_column('parcels', 'owner_id')
    op.drop_table('users')
    # ### end Alembic commands ###
